print("Hello, World!")
print("This is a sample Python script.")
print("It demonstrates basic print statements.")
print("You can use print to display text, numbers, and variables.")
print("For example, let's print a number:")
