print("Hello, World!")
print("This is a sample Python script.")
print("It demonstrates basic print statements.")
print("You can use print to display text, numbers, and variables.")
print("For example, let's print a number:")
print("The number is:", 42)
print("You can also print multiple items in one statement:")
print("The number is:", 42, "and its square is:", 42 ** 2)